### ISSUE TITLE
Add monitoring for asset pool balances in secondary bridge

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega-monitoring#30]
# Backkground

We have a `network_balances` service that publishes network balances from Vega and from the mainnet Ethereum asset pool. We use the Vega database from the locally running data node and the Etherscan API.

# Issue

Currently, We support only balance on the asset pool deployed to the mainnet ethereum. We are going to deploy a secondary bridge to the Arbitrum One soon and We want to have monitoring there are no missing funds on the Arbitrum.

# TODOs

- [x] Update vega-monitoring to publish balance on the secondary asset pool
- [x] Update dashboard for asset pool balances (https://monitoring.vega.community/d/mainnet-asset-balances/asset-balances?orgId=1)
- [x] Update alert (https://monitoring.vega.community/alerting/grafana/e5001f5b-e4db-451d-b509-d9860d23153d/view?returnTo=%2Falerting%2Flis)
- [ ] Once the mainnet is released test changes on m3.vega.community
- [ ] Merge changes
- [ ] Release new binary (create tag)
- Update configs in ansible
    - [ ] The binary version (https://github.com/vegaprotocol/ansible/blob/master/inventories/mainnet.yaml#L149)
    - [ ] The vega-monitoring config (https://github.com/vegaprotocol/ansible/blob/master/roles/vega-monitoring/templates/config-mainnet.toml.j2)
- [ ] Release to other servers

**Comment by ValentinTrinque** [comment]
Update dashboard for asset pool balances

```sql
WITH asset_pool AS (
  SELECT asset_id, chain_id, last(balance, balance_time) AS last_balance, last(balance_time, balance_time) AS balance_time FROM metrics.network_balances
  WHERE balance_source = 'ASSET_POOL' GROUP BY asset_id, chain_id
), vega_network AS (
  SELECT asset_id, last(balance, balance_time) AS last_balance, last(balance_time, balance_time) AS balance_time FROM metrics.network_balances
  WHERE balance_source = 'PARTIES_TOTAL' GROUP BY asset_id
), unrealised_withdrawals AS (
  SELECT asset_id, last(balance, balance_time) AS last_balance, last(balance_time, balance_time) AS balance_time FROM metrics.network_balances
  WHERE balance_source = 'UNREALISED_WITHDRAWALS_TOTAL' GROUP BY asset_id
), unfinalized_deposits AS (
  SELECT asset_id, last(balance, balance_time) AS last_balance, last(balance_time, balance_time) AS balance_time FROM metrics.network_balances
  WHERE balance_source = 'UNFINALIZED_DEPOSITS' GROUP BY asset_id
)
SELECT
  a.name AS "Asset Name",
  ap.chain_id AS "Chain ID",
  (ap.last_balance - vn.last_balance - uw.last_balance - ud.last_balance)::decimal / 10 ^ a.decimals AS "Balance",
  a.symbol AS "Asset",
  ap.balance_time AS "Time",
  ap.last_balance::decimal / 10 ^ a.decimals AS "Asset Pool",
  vn.last_balance::decimal / 10 ^ a.decimals AS "Vega Network",
  uw.last_balance::decimal / 10 ^ a.decimals AS "Unrealised Withdrawals",
  ud.last_balance::decimal / 10 ^ a.decimals AS "Unfinalized Deposits"
FROM assets_current a
LEFT JOIN asset_pool ap ON ap.asset_id = a.id
LEFT JOIN vega_network vn ON vn.asset_id = a.id
LEFT JOIN unrealised_withdrawals uw ON uw.asset_id = a.id
LEFT JOIN unfinalized_deposits ud ON ud.asset_id = a.id
GROUP BY a.id, a.name, a.symbol, ap.balance_time, a.decimals, ap.last_balance, vn.last_balance, uw.last_balance, ud.last_balance;
```

**Comment by ValentinTrinque** [comment]
Update alert

```sql
WITH asset_pool AS (
  SELECT asset_id, chain_id, last(balance, balance_time) AS last_balance FROM metrics.network_balances
  WHERE balance_source = 'ASSET_POOL' GROUP BY asset_id
), vega_network AS (
  SELECT asset_id, last(balance, balance_time) AS last_balance FROM metrics.network_balances
  WHERE balance_source = 'PARTIES_TOTAL' GROUP BY asset_id
), unrealised_withdrawals AS (
  SELECT asset_id, last(balance, balance_time) AS last_balance FROM metrics.network_balances
  WHERE balance_source = 'UNREALISED_WITHDRAWALS_TOTAL' GROUP BY asset_id
), unfinalized_deposits AS (
  SELECT asset_id, last(balance, balance_time) AS last_balance FROM metrics.network_balances
  WHERE balance_source = 'UNFINALIZED_DEPOSITS' GROUP BY asset_id
)
SELECT
  (ap.last_balance - vn.last_balance - uw.last_balance - ud.last_balance)::decimal / 10 ^ a.decimals AS balance,
  a.name, a.symbol, ap.chain_id, a.decimals::text,
  (ap.last_balance::decimal / 10 ^ a.decimals)::text AS asset_pool_balance,
  (vn.last_balance::decimal / 10 ^ a.decimals)::text AS vega_network_balance,
  (uw.last_balance::decimal / 10 ^ a.decimals)::text AS unrealised_withdrawals_balance,
  (ud.last_balance::decimal / 10 ^ a.decimals)::text AS unfinalized_deposits_balance
FROM assets_current a
LEFT JOIN asset_pool ap ON ap.asset_id = a.id
LEFT JOIN vega_network vn ON vn.asset_id = a.id
LEFT JOIN unrealised_withdrawals uw ON uw.asset_id = a.id
LEFT JOIN unfinalized_deposits ud ON ud.asset_id = a.id
GROUP BY a.id, a.name, a.symbol, a.decimals, ap.last_balance, vn.last_balance, uw.last_balance, ud.last_balance;
```
